import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { getUser } from '@/lib/db/queries';
import { UserProvider } from '@/lib/auth';
import { Header } from './header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let userPromise = getUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider userPromise={userPromise}>
          <div className="min-h-screen bg-gray-50 text-gray-900 font-sans">
            <Header />
            {children}
            <footer className="py-12 border-t border-gray-100">
              <div className="max-w-6xl mx-auto px-8">
                <div className="flex flex-col md:flex-row justify-between items-center">
                  <div className="text-xl font-light tracking-widest mb-6 md:mb-0">
                    NOTHING
                  </div>
                  <div className="text-sm text-gray-500">
                    © 2025 Nothing™ — All rights reserved to nothing
                  </div>
                </div>
              </div>
            </footer>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
