name: CI

on:
  push:
    branches: [main, develop]   # pas aan naar jouw flow
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 0. Repo klonen
      - uses: actions/checkout@v4

      # 1. PNPM installeren (moet vóór setup-node omdat we de pnpm-cache gebruiken)
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false      # we installeren zelf straks

      # 2. Node installeren en pnpm-cache activeren
      - uses: actions/setup-node@v3
        with:
          node-version: 18        # zelfde major als lokaal
          cache: pnpm             # werkt nu omdat pnpm al is geïnstalleerd

      # 3. Dependencies
      - run: pnpm install --frozen-lockfile

      # 4. Lint + type-check
      - run: pnpm lint

      # 5. Tests (wordt overgeslagen als je nog geen tests hebt)
      - run: pnpm test --if-present

      # 6. Build (vergelijkbaar met Vercel)
      - run: pnpm build
