name: CI

on:
  push:
    branches: [main, develop]      # pas aan naar wens
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 0️⃣ Repo klonen
      - uses: actions/checkout@v4

      # 1️⃣ Node installeren
      - uses: actions/setup-node@v3
        with:
          node-version: 18         # dezelfde major als lokaal

      # 2️⃣ PNPM installeren
      - uses: pnpm/action-setup@v2
        with:
          version: 18

      # 3️⃣ Dependencies
      - run: pnpm install --frozen-lockfile

      # 4️⃣ Lint + type-check
      - run: pnpm lint

      # 5️⃣ Tests (wordt overgeslagen als je er geen hebt)
      - run: pnpm test --if-present

      # 6️⃣ Build
      - run: pnpm build
