name: CI

on:
  push:
    branches: [main, develop]   # pas aan naar jouw flow
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 0. Repo klonen
      - uses: actions/checkout@v4

      # 1. Node installeren
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18        # gebruik dezelfde major die lokaal staat
          cache: 'pnpm'

      # 2. PNPM klaarzetten
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # 3. Dependencies installeren
      - run: pnpm install --frozen-lockfile

      # 4. Lint + typecheck
      - run: pnpm lint

      # 5. Tests (slaat stap over als je nog niets hebt)
      - run: pnpm test --if-present

      # 6. Build (vergelijkbaar met wat Vercel doet)
      - run: pnpm build
